"""Adding last_name and dob to users

Revision ID: 1c8040ae118a
Revises: 6bb8410c5c88
Create Date: 2020-11-19 12:27:08.016852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1c8040ae118a"
down_revision = "6bb8410c5c88"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("dob", sa.Date(), nullable=True))
    op.add_column("users", sa.Column("last_name", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_name")
    op.drop_column("users", "dob")
    # ### end Alembic commands ###
