"""Add table invites

Revision ID: 227bb6b8bdea
Revises: f3814cfbfd27
Create Date: 2020-11-12 13:48:29.157004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "227bb6b8bdea"
down_revision = "f3814cfbfd27"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_inviting_id", sa.Integer(), nullable=False),
        sa.Column("user_invited_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_invited_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_inviting_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("invites")
    # ### end Alembic commands ###
