"""Adding is_active to console model

Revision ID: 3b4f2a2aae35
Revises: 79713ce1488b
Create Date: 2020-12-30 13:29:15.623513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3b4f2a2aae35"
down_revision = "79713ce1488b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "consoles",
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("consoles", "is_active")
    # ### end Alembic commands ###
