"""Add friendships table

Revision ID: 3c18c08b9f0c
Revises: 73b4301480dd
Create Date: 2020-10-28 15:30:12.699347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3c18c08b9f0c"
down_revision = "73b4301480dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friendships",
        sa.Column("follower_id", sa.Integer(), nullable=False),
        sa.Column("followed_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["followed_id"], ["users.id"],),
        sa.ForeignKeyConstraint(["follower_id"], ["users.id"],),
        sa.PrimaryKeyConstraint("follower_id", "followed_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("friendships")
    # ### end Alembic commands ###
