"""Adding game.url

Revision ID: 3e30d8b82e1f
Revises: 52c512af051f
Create Date: 2021-02-26 16:57:58.819703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3e30d8b82e1f"
down_revision = "52c512af051f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("url", sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "url")
    # ### end Alembic commands ###
