"""Creates challenge_users table

Revision ID: 4e57aed14444
Revises: eaadedf44806
Create Date: 2020-10-22 17:49:10.496736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4e57aed14444"
down_revision = "eaadedf44806"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "challenge_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("challenger_id", sa.Integer(), nullable=True),
        sa.Column("challenged_id", sa.Integer(), nullable=False),
        sa.Column("wager_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=45), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["challenged_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["challenger_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wager_id"],
            ["challenges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("challenge_users")
    # ### end Alembic commands ###
