"""Adding challenger sms status

Revision ID: 52c512af051f
Revises: 2b690a3c1c55
Create Date: 2021-02-17 18:32:19.306743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "52c512af051f"
down_revision = "2b690a3c1c55"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "challenge_users", sa.Column("challenged_sms_sent", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "challenge_users", sa.Column("challenger_sms_sent", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("challenge_users", "challenger_sms_sent")
    op.drop_column("challenge_users", "challenged_sms_sent")
    # ### end Alembic commands ###
