"""Adds challenges columns and games

Revision ID: 5a10f051a884
Revises: 0b0f28b15b39
Create Date: 2020-10-20 17:21:43.631682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5a10f051a884"
down_revision = "0b0f28b15b39"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "challenges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=45), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("buy_in", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("reward", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("status", sa.String(length=45), nullable=False),
        sa.Column("due_date", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "games",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.add_column("games", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "updated_at")
    op.drop_column("games", "created_at")
    op.drop_table("challenges")
    # ### end Alembic commands ###
