"""Adding is_direct field to challenges

Revision ID: 62afd70caa61
Revises: b21cd8c4561f
Create Date: 2020-12-08 15:44:32.974487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "62afd70caa61"
down_revision = "b21cd8c4561f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("challenges", sa.Column("is_direct", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("challenges", "is_direct")
    # ### end Alembic commands ###
