"""Add is private field

Revision ID: 6625485d4e8b
Revises: de3759a2c218
Create Date: 2020-11-09 13:56:58.485395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6625485d4e8b"
down_revision = "de3759a2c218"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_private", sa.Boolean(), nullable=True, server_default=sa.text("false")
        ),
    )
    op.drop_column("users", "allow_public_challenges")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "allow_public_challenges",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("users", "is_private")
    # ### end Alembic commands ###
