"""Adding cascade to game_has_console_table

Revision ID: 6bb8410c5c88
Revises: 227bb6b8bdea
Create Date: 2020-11-18 14:20:37.121212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb8410c5c88'
down_revision = '227bb6b8bdea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('games_has_consoles_console_id_fkey', 'games_has_consoles', type_='foreignkey')
    op.drop_constraint('games_has_consoles_game_id_fkey', 'games_has_consoles', type_='foreignkey')
    op.create_foreign_key(None, 'games_has_consoles', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'games_has_consoles', 'consoles', ['console_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games_has_consoles', type_='foreignkey')
    op.drop_constraint(None, 'games_has_consoles', type_='foreignkey')
    op.create_foreign_key('games_has_consoles_game_id_fkey', 'games_has_consoles', 'games', ['game_id'], ['id'])
    op.create_foreign_key('games_has_consoles_console_id_fkey', 'games_has_consoles', 'consoles', ['console_id'], ['id'])
    # ### end Alembic commands ###
