"""Wager id is now unique

Revision ID: 707baa1bc549
Revises: 8c1eb5ff3124
Create Date: 2020-12-21 15:11:03.287808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "707baa1bc549"
down_revision = "8c1eb5ff3124"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "challenge_users", ["wager_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "challenge_users", type_="unique")
    # ### end Alembic commands ###
