"""Adding user game table

Revision ID: 73b4301480dd
Revises: a43ff39d86da
Create Date: 2020-10-26 17:13:32.160765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "73b4301480dd"
down_revision = "a43ff39d86da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("console_id", sa.Integer(), nullable=True),
        sa.Column("level", sa.String(length=45), nullable=False),
        sa.Column("gamertag", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["console_id"],
            ["consoles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("games_has_users")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games_has_users",
        sa.Column("game_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=45), autoincrement=False, nullable=False),
        sa.Column(
            "gamertag", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name="games_has_users_game_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="games_has_users_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("game_id", "user_id", name="games_has_users_pkey"),
    )
    op.drop_table("user_games")
    # ### end Alembic commands ###
