"""Adding playing days to user

Revision ID: 79713ce1488b
Revises: 707baa1bc549
Create Date: 2020-12-28 19:43:20.275380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "79713ce1488b"
down_revision = "707baa1bc549"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("playing_days", sa.String(length=16), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "playing_days")
    # ### end Alembic commands ###
