"""Adding console_id to challenges

Revision ID: b21cd8c4561f
Revises: c85d6a8b7a6e
Create Date: 2020-12-03 16:46:28.300214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b21cd8c4561f"
down_revision = "c85d6a8b7a6e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("challenges", sa.Column("console_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "challenges", "consoles", ["console_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "challenges", type_="foreignkey")
    op.drop_column("challenges", "console_id")
    # ### end Alembic commands ###
