"""Adding description to game model

Revision ID: b712ac7a14b3
Revises: e4656c5f1088
Create Date: 2021-02-08 15:01:33.927073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b712ac7a14b3"
down_revision = "e4656c5f1088"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "description")
    # ### end Alembic commands ###
