"""Adding default status for challenger

Revision ID: c85d6a8b7a6e
Revises: eea351e43e23
Create Date: 2020-12-01 16:28:29.190113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c85d6a8b7a6e"
down_revision = "eea351e43e23"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "challenge_users", "challenged_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "challenge_users", "challenger_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "challenge_users",
        "status_challenged",
        existing_type=sa.VARCHAR(length=45),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "challenge_users",
        "status_challenged",
        existing_type=sa.VARCHAR(length=45),
        nullable=False,
    )
    op.alter_column(
        "challenge_users", "challenger_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "challenge_users", "challenged_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
