"""Adding confirmations table

Revision ID: cb2b414ca670
Revises: f2c67b529235
Create Date: 2020-10-19 14:23:17.852648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cb2b414ca670"
down_revision = "f2c67b529235"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "confirmations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("expire_at", sa.Integer(), nullable=False),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("confirmations")
    # ### end Alembic commands ###
