"""Adding foreign key to challenges.game_id

Revision ID: ed3ef13c92a2
Revises: 5a10f051a884
Create Date: 2020-10-20 17:39:13.442263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ed3ef13c92a2"
down_revision = "5a10f051a884"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "challenges", "games", ["game_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "challenges", type_="foreignkey")
    # ### end Alembic commands ###
