"""Adding fields status_challenger and status_challenged

Revision ID: eea351e43e23
Revises: dd8fcd114129
Create Date: 2020-12-01 15:47:19.065994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eea351e43e23"
down_revision = "dd8fcd114129"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "challenge_users",
        sa.Column("status_challenged", sa.String(length=45), nullable=False),
    )
    op.add_column(
        "challenge_users",
        sa.Column("status_challenger", sa.String(length=45), nullable=False),
    )
    op.drop_column("challenge_users", "status")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "challenge_users",
        sa.Column("status", sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    )
    op.drop_column("challenge_users", "status_challenger")
    op.drop_column("challenge_users", "status_challenged")
    # ### end Alembic commands ###
