"""Creates a user table

Revision ID: f2c67b529235
Revises: 
Create Date: 2020-10-13 15:32:24.117194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f2c67b529235"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=255), nullable=True),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("firebase_id", sa.String(length=255), nullable=False),
        sa.Column("accepted_terms", sa.Boolean(), nullable=True),
        sa.Column("playing_hours_begin", sa.Integer(), nullable=True),
        sa.Column("playing_hours_end", sa.Integer(), nullable=True),
        sa.Column("range_bet_low", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("range_bet_high", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("firebase_id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
