"""Add unique_user_game_constraint

Revision ID: f3814cfbfd27
Revises: 6625485d4e8b
Create Date: 2020-11-10 17:22:00.285251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f3814cfbfd27"
down_revision = "6625485d4e8b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_user_game_constraint",
        "user_games",
        ["console_id", "game_id", "user_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_user_game_constraint", "user_games", type_="unique")
    # ### end Alembic commands ###
