version: "3.7"

services:
  # Our own application
  app:
    build: .
    volumes:
      - ./app:/app
      - ./.env:/app/.env
    command: flask run --host 0.0.0.0
    env_file: .env

  # NGINX to serve the app
  nginx:
    image: nginx:1.19.1
    volumes:
      - ./nginx-config/:/etc/nginx/conf.d
    depends_on:
      - app
    ports:
      - 80:80
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
