version: "3.7"

services:
  # Our own application
  app:
    build: .
    volumes:
      - ./app:/app
      - ./.env:/app/.env
    ports:
      - 5000:5000
    command: flask run --host 0.0.0.0
    env_file: .env
    depends_on:
      - db

  # Development mail daemon.
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025

  # Our Posrgres DB.
  db:
    image: postgres:12.4-alpine
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # To quickly check the DB.
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 8081:80
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=test

  # To check docker logs.
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
