"""Add avatar field to users

Revision ID: 3a6a13117d7b
Revises: 899d01588a35
Create Date: 2020-10-26 10:25:42.475088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3a6a13117d7b"
down_revision = "899d01588a35"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("avatar", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar")
    # ### end Alembic commands ###
