"""Add is_active field to game model

Revision ID: 62e792e3e04f
Revises: 3a6a13117d7b
Create Date: 2020-10-26 10:56:52.455089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "62e792e3e04f"
down_revision = "3a6a13117d7b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "is_active")
    # ### end Alembic commands ###
