"""Creates results_1v1 table

Revision ID: 630fe436a440
Revises: 4e57aed14444
Create Date: 2020-10-23 12:01:17.820349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "630fe436a440"
down_revision = "4e57aed14444"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "results_1v1",
        sa.Column("challenge_id", sa.Integer(), nullable=False),
        sa.Column("score_player_1", sa.Integer(), nullable=False),
        sa.Column("score_player_2", sa.Integer(), nullable=False),
        sa.Column("player_1_id", sa.Integer(), nullable=False),
        sa.Column("player_2_id", sa.Integer(), nullable=False),
        sa.Column("played", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["challenge_id"], ["challenges.id"],),
        sa.ForeignKeyConstraint(["player_1_id"], ["users.id"],),
        sa.ForeignKeyConstraint(["player_2_id"], ["users.id"],),
        sa.PrimaryKeyConstraint("challenge_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("results_1v1")
    # ### end Alembic commands ###
