"""Adding user.is_active column to users table

Revision ID: 667dc1080845
Revises: cb2b414ca670
Create Date: 2020-10-20 13:11:59.832683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "667dc1080845"
down_revision = "cb2b414ca670"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=True,
            server_default=sa.schema.DefaultClause("True"),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###
