"""Creates user photo model

Revision ID: 899d01588a35
Revises: 64eabdd635e6
Create Date: 2020-10-23 19:18:58.741247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "899d01588a35"
down_revision = "64eabdd635e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=True),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=45), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_photos")
    # ### end Alembic commands ###
