"""Adding games_has_users table

Revision ID: a43ff39d86da
Revises: c40b6ed352de
Create Date: 2020-10-26 12:09:03.721354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a43ff39d86da"
down_revision = "c40b6ed352de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games_has_users",
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(length=45), nullable=False),
        sa.Column("gamertag", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"],),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"],),
        sa.PrimaryKeyConstraint("game_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("games_has_users")
    # ### end Alembic commands ###
