"""Adding allow_public_challenges column to user

Revision ID: eaadedf44806
Revises: ed3ef13c92a2
Create Date: 2020-10-21 14:02:00.096831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eaadedf44806"
down_revision = "ed3ef13c92a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "allow_public_challenges",
            sa.Boolean(),
            server_default=sa.schema.DefaultClause("True"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "allow_public_challenges")
    # ### end Alembic commands ###
