name: Deploy to development

on:
  pull_request:
    branches: [develop]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ secrets.DOCKER_GITHUB_USER }}
          password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}

      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo git rev-parse --short HEAD)

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: PlayTopDog/application_backend:{{steps.vars.outputs.tag}}

      - name: Execute deploy command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_DEVELOPMENT_HOST }}
          username: ${{ secrets.AWS_DEVELOPMENT_USER }}
          key: ${{ secrets.AWS_DEVELOPMENT_PEM }}
          script: ./deploy
