name: Deploy to development

on:
  push:
    branches: [develop]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Upload files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_DEVELOPMENT_HOST }}
          username: ${{ secrets.AWS_DEVELOPMENT_USER }}
          key: ${{ secrets.AWS_DEVELOPMENT_PEM }}
          source: "."
          target: "app"

      - name: Execute deploy command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_DEVELOPMENT_HOST }}
          username: ${{ secrets.AWS_DEVELOPMENT_USER }}
          key: ${{ secrets.AWS_DEVELOPMENT_PEM }}
          script: ./deploy
