name: Deploy to development

on:
  push:
    branches: [develop]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@master

      - name: Upload files
        uses: appleboy/scp-action@master
        with:
          host: ec2-3-138-245-30.us-east-2.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.AWS_DEVELOPMENT_PEM }}
          source: "."
          target: "app"

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-138-245-30.us-east-2.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.AWS_DEVELOPMENT_PEM }}
          script: ./deploy
